### ISSUE TITLE
Resolver times out

### ISSUE THREAD

**Issue by Benjamin-Lee** [mcs07/CIRpy#5]
I just installed CIRpy and tried it out, but got this error, even though my internet is fine:

```python
>>> from cirpy import Molecule
>>> Molecule("water")
Molecule(input='water', resolvers=None, get3d=False, kwargs={})
>>> Molecule("water").formula
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/BenjaminLee/Desktop/Python/Research/flow-chem/env/lib/python3.6/site-packages/cirpy.py", line 296, in fget_memoized
    setattr(self, attr_name, fget(self))
  File "/Users/BenjaminLee/Desktop/Python/Research/flow-chem/env/lib/python3.6/site-packages/cirpy.py", line 384, in formula
    return resolve(self.input, 'formula', self.resolvers, **self.kwargs)
  File "/Users/BenjaminLee/Desktop/Python/Research/flow-chem/env/lib/python3.6/site-packages/cirpy.py", line 192, in resolve
    results = query(input, representation, resolvers, False, get3d, **kwargs)
  File "/Users/BenjaminLee/Desktop/Python/Research/flow-chem/env/lib/python3.6/site-packages/cirpy.py", line 162, in query
    tree = request(input, representation, resolvers, get3d, tautomers, **kwargs)
  File "/Users/BenjaminLee/Desktop/Python/Research/flow-chem/env/lib/python3.6/site-packages/cirpy.py", line 95, in request
    response = urlopen(url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>```

**Comment by mcs07** [comment]
The NCI resolver appears to be down: http://cactus.nci.nih.gov/chemical/structure

**Comment by Benjamin-Lee** [comment]
Yup, it works now! Thanks for the help.
